---
abstract: 'Database handles ready for testing'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  File::Find: '0'
  File::Temp: '0'
  List::Util: '0'
  SQL::Statement: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Database
recommends:
  DBD::CSV: '0.30'
  DBD::SQLite: '1.27'
requires:
  Carp: '0'
  Cwd: '0'
  DBD::DBM: '0'
  DBI: '0'
  File::HomeDir: '0'
  File::Path: '0'
  File::Spec: '0'
  YAML::Tiny: '1.62'
  perl: '5.006'
  strict: '0'
  version: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-Database
  repository: http://github.com/book/Test-Database.git
version: '1.113'
