---
name: Test-Database
version: 0.02
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
abstract: Database handles ready for testing
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  DBI: 1
  Test::More: 0
provides:
  Test::Database:
    file: lib/Test/Database.pm
    version: 0.02
  Test::Database::Driver:
    file: lib/Test/Database/Driver.pm
  Test::Database::Driver::CSV:
    file: lib/Test/Database/Driver/CSV.pm
  Test::Database::Driver::DBM:
    file: lib/Test/Database/Driver/DBM.pm
  Test::Database::Driver::SQLite:
    file: lib/Test/Database/Driver/SQLite.pm
  Test::Database::Driver::mysql:
    file: lib/Test/Database/Driver/mysql.pm
  Test::Database::Handle:
    file: lib/Test/Database/Handle.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
